# Generated by Django 5.1.7 on 2025-03-06 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Intitulé du compte')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code du compte')),
                ('type', models.CharField(choices=[('ACTIF', 'Actif'), ('PASSIF', 'Passif'), ('PRODUIT', 'Produit'), ('CHARGE', 'Charge')], max_length=10, verbose_name='Type du compte')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Solde actuel')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name="Date de l'opération")),
                ('description', models.CharField(max_length=255, verbose_name="Libellé de l'opération")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Montant de l'opération")),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='accounting.account', verbose_name='Compte crédité')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_transactions', to='accounting.account', verbose_name='Compte débité')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Utilisateur ayant effectué l'opération")),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.transaction', verbose_name='Transaction')),
            ],
        ),
    ]
